AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
  Excludes:
    - libraries/**
    - providers/**
    - recipes/**
    - resources/**
    - spec/**

Encoding:
    Exclude:
      - metadata.rb
      - Gemfile

LineLength:
  Enabled: false

WordArray:
  MinSize: 3
